# Basic configuration for CodeRabbit AI
# Code quality, security, and style checks for a Joomla extension

# List of tools
tools:
  - name: "phpcs"
    args: "--standard=Joomla src/"  # Set Joomla coding standard

  - name: "eslint"
    args: "--config .eslintrc.js src/"  # If JavaScript files need linting with ESLint

# Exclusions
exclude_paths:
  - "node_modules/"
  - "vendor/"
  - "build/"
  - "tests/"

# Optional: Define specific languages if supported
languages:
  - php
  - javascript
  - html
  - css

# Specify CI/CD integration if required by CodeRabbit
ci_cd:
  provider: "github"
  config_file: ".github/workflows/php.yml"
