# .coderabbit.yaml
# Simplified configuration for CodeRabbit AI for a Joomla extension

# Code quality and linting
php:
  linter: "phpcs"
  standard: "Joomla"

javascript:
  linter: "eslint"
  config: "recommended"

html:
  linter: "htmlhint"

css:
  linter: "stylelint"

# Exclude directories and files that should not be analyzed
exclude:
  - "node_modules"
  - "vendor"
  - "build"
  - "tests"
  - "*.min.js"
  - "*.min.css"
