language: "en"

early_access: false

reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!**/.xml"
  path_instructions:
    - path: "**/*.js"
      instructions: "Review the JavaScript code for conformity with the Google JavaScript style guide, highlighting any deviations."
    - path: "**/*.php"
      instructions: "Review the PHP code for Joomla coding standards compliance. Ensure adherence to best practices for Joomla extensions, including MVC structure, security practices, and Joomla-specific function usage."
    - path: "**/*.ts"
      instructions: |
        "Review the JavaScript code for conformity with the Google JavaScript style guide, highlighting any deviations. Ensure that:
        - The code adheres to best practices associated with nodejs.
        - The code adheres to best practices associated with nestjs framework.
        - The code adheres to best practices recommended for performance.
        - The code adheres to similar naming conventions for controllers, models, services, methods, variables."
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
    - "master"
    - "dev"
    - "feat/*"
    - "feat-*"
    - "release-*"

chat:
  auto_reply: true
